// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function updateAvailable() {
    return invoke<boolean>("update_available")
}

export function getDownloadUrl() {
    return invoke<string>("get_download_url")
}

export function extractUpdate() {
    return invoke<null>("extract_update")
}

export function runGame() {
    return invoke<number>("run_game")
}

export function openDir(path: string) {
    return invoke<null>("open_dir", { path })
}


