// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function updateAvailable() {
    return invoke<boolean>("update_available")
}

export function downloadLatest() {
    return invoke<boolean>("download_latest")
}

export function runGame() {
    return invoke<null>("run_game")
}


